runtime: python311
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker stock_monitoring_backend.asgi:application

instance_class: F2  # Smallest instance class
automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1  # Keep one instance running to avoid cold starts
  max_instances: 2  # Restrict scaling to keep costs low

env_variables:
  DJANGO_SETTINGS_MODULE: stock_monitoring_backend.settings
  GOOGLE_CLOUD_PROJECT: "spring-nova-435423-t7"

# Define which files to include or exclude in the deployment
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
